# Generated by Django 3.1.3 on 2021-01-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.TextField(default='null'),
        ),
    ]
